import { FileCheck, ArrowLeft } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';

type LegalLanguage = 'en' | 'zh' | 'ja';

type TermsSection = {
  title?: string;
  paragraphs?: string[];
  items?: string[];
};

const termsContent: Record<LegalLanguage, {
  back: string;
  title: string;
  effectiveDate: string;
  sections: TermsSection[];
  operator: string;
  siteName: string;
}> = {
  en: {
    back: 'Back to Home',
    title: 'Terms of Service',
    effectiveDate: 'Effective date: March 31, 2026',
    operator: 'Operator: VAID Company',
    siteName: 'Website name: VAID',
    sections: [
      { paragraphs: ['Welcome to VAID (the “Service”). The Service is operated and provided by VAID Company.', 'Before accessing, registering for, using, or purchasing paid content related to the Service, please carefully read and fully understand these Terms. By accessing or using the Service, you are deemed to have read, understood, and agreed to be bound by all terms. If you do not agree, please stop using the Service immediately.'] },
      { title: '1. Nature of the Service', paragraphs: ['VAID is an online service for digital content display, record assistance, verification assistance, and related support. It helps users generate digital certificates, display relevant information, provide verification results, and create supporting materials.', 'The Service provides technical and informational display support only. It does not constitute copyright registration, ownership confirmation, notarization, judicial certification, administrative approval, or endorsement by any government, court, arbitration, or registration authority.', 'Digital certificates, verification information, and related materials generated or displayed by the Service are reference materials for explanation, display, or auxiliary evidence only. They do not automatically become legal proof of ownership, originality, legality, or authenticity.'] },
      { title: '2. User Commitments', paragraphs: ['When using the Service, you represent and warrant that:'], items: ['You have lawful rights to, or valid authorization for, the content you upload, submit, generate, display, or otherwise use.', 'Your content does not infringe any third party copyright, trademark, patent, portrait right, reputation right, privacy right, personal information right, or other lawful rights.', 'You will not upload, publish, transmit, store, or display illegal, infringing, false, fraudulent, defamatory, obscene, violent, terrorist, discriminatory, harassing, harmful-to-minors, or otherwise inappropriate content.', 'You will not use the Service for activities that violate laws, public order, good customs, or others’ lawful rights.', 'You will not interfere with, damage, attack, reverse exploit, or improperly use the Service, systems, pages, interfaces, workflows, or rules.'] },
      { paragraphs: ['Any dispute, complaint, report, claim, administrative penalty, judicial process, or legal liability arising from your content or use is your responsibility. If VAID or any third party suffers loss, you shall bear liability according to law.'] },
      { title: '3. Service Content', paragraphs: ['The Service may provide the following content or functions:'], items: ['Upload images and generate VAID digital certificates and related display content.', 'Generate verification information, query results, and supporting display pages corresponding to content.', 'Provide online verification, record display, and related supporting material downloads.', 'Provide order management, credit management, activation-code issuance, and usage support.', 'Provide page display, technical support, and customer service related to the above.'] },
      { paragraphs: ['VAID may adjust, interrupt, restrict, change, upgrade, or discontinue service content, modules, page design, delivery methods, usage rules, pricing, or workflows for business development, operation, user experience, technical upgrades, compliance, or other reasonable needs, while making reasonable efforts to maintain major service availability.'] },
      { title: '4. Digital Certificates and Verification Information', paragraphs: ['You understand and agree that:'], items: ['Digital certificates generated by the Service are mainly for content display, record explanation, and auxiliary proof.', 'Verification information, query results, supporting materials, and related pages are used to help explain generation, display, or record status.', 'Online verification pages, links, QR codes, query results, or downloads are auxiliary checking and explanation tools, and do not automatically constitute final proof of ownership, authenticity, originality, legality, or validity.', 'The Service does not guarantee that any institution, platform, court, arbitration body, administrative authority, or other entity will recognize, accept, or rely on any materials generated or displayed by the Service.'] },
      { paragraphs: ['You should properly preserve original files, order information, digital certificates, verification information, downloaded files, and other necessary materials. Consequences caused by your failure to preserve them are borne by you.'] },
      { title: '5. Payment and Refunds', paragraphs: ['If paid features are provided, please confirm plan details, price, usage rules, and scope before purchase.', 'You agree that:'], items: ['After successful payment, the system will issue corresponding rights or credits according to the order.', 'Credits or activation codes that have been issued and can be used normally are generally non-refundable.', 'If payment succeeds but credits or activation codes are not received, you may contact customer support through the “Contact Us” entry.', 'If a system reason causes missing or unusable credits or activation codes, the Service will reissue or reasonably handle them after verification.', 'Consumed portions are deemed used; only unused portions may be reissued or otherwise reasonably handled.', 'Losses caused by incorrect input, poor safekeeping, transfer, disclosure, or other user-side reasons are borne by the user.', 'For payment delays, status desynchronization, or temporary issues caused by payment channels, network failures, third-party platforms, or other causes beyond reasonable control, the Service will assist within a reasonable scope but is not liable for matters beyond such control.'] },
      { title: '6. Access Control', paragraphs: ['The Service may use order information, activation codes, access credentials, device environment, cached information, or other necessary means for service verification, benefit recognition, usage management, and security control.', 'You understand and agree that:'], items: ['Such information is used only for service delivery, order association, usage management, security, and experience optimization.', 'Such identification information does not necessarily equal real identity authentication.', 'You should properly keep order, activation code, or other access credential information.', 'Losses caused by your disclosure, transfer, sharing, loss, or poor safekeeping are borne by you.'] },
      { title: '7. Third-Party Services', paragraphs: ['The Service may depend on third-party payment, cloud storage, databases, network services, infrastructure, or other third-party services.', 'If third-party failures, delays, interruptions, restrictions, adjustments, upgrades, policy changes, or other causes beyond VAID’s reasonable control affect part or all of the Service, VAID is not liable for consequences beyond reasonable control to the extent permitted by law, but will make reasonable efforts to assist or restore.'] },
      { title: '8. Intellectual Property', paragraphs: ['Except for user-uploaded content to which users lawfully hold rights, all trademarks, logos, names, interface designs, page layouts, texts, images, code, structure, data organization, service rules, and related content of the Service belong to VAID or relevant rights holders.', 'Without prior written permission from VAID or relevant rights holders, no one may copy, distribute, modify, adapt, compile, translate, rent, sell, reverse engineer, decompile, disassemble, or otherwise improperly use Service-related content.'] },
      { title: '9. Disclaimer', paragraphs: ['To the maximum extent permitted by law, the Service is provided “as is” and “as available”. VAID makes no express or implied warranties that:'], items: ['The Service will be completely error-free, uninterrupted, delay-free, vulnerability-free, or permanently available.', 'Content generated or displayed by the Service will necessarily be accepted by any third party.', 'Digital certificates, verification information, or supporting materials can replace legal procedures.', 'User-uploaded content is necessarily original, lawful, complete, true, or capable of ownership confirmation.', 'Results obtained through the Service will meet any particular purpose or expectation.'] },
      { paragraphs: ['VAID is not liable beyond the scope required by law for losses caused by force majeure, system maintenance, network failures, hacker attacks, viruses, third-party service abnormalities, policy changes, regulatory requirements, or other unforeseeable, unavoidable, or uncontrollable causes.'] },
      { title: '10. Changes to Terms', paragraphs: ['VAID may modify or update these Terms based on business needs, operation arrangements, laws and regulations, or compliance requirements.', 'If material changes occur, VAID will notify users through website announcements, page prompts, or other reasonable methods. Updated Terms take effect once published or on the stated effective date. Continued use after updates means you accept the updated Terms.'] },
      { title: '11. Governing Law and Dispute Resolution', paragraphs: ['The formation, validity, interpretation, performance, and dispute resolution of these Terms are governed by the laws of the People’s Republic of China.', 'Any dispute arising from these Terms or the Service should first be resolved through friendly negotiation. If negotiation fails, either party may file a lawsuit with the competent court where VAID Company is located.'] },
      { title: '12. Miscellaneous', paragraphs: ['If any provision is found invalid, unlawful, or unenforceable, the validity and enforceability of other provisions will not be affected.', 'Section headings are for convenience only and do not affect interpretation.', 'Matters not covered by these Terms shall be handled according to laws, regulations, and VAID page rules. If page rules conflict with these Terms, specific rules expressly stated for the relevant scenario prevail unless laws provide otherwise.'] }
    ]
  },
  zh: {
    back: '返回首页',
    title: '用户协议',
    effectiveDate: '生效日期：2026年3月31日',
    operator: '运营方：VAID Company',
    siteName: '网站名称：VAID',
    sections: [
      { paragraphs: ['欢迎使用 VAID（以下简称“本服务”）。本服务由 VAID Company 运营并提供。', '在访问、注册、使用本服务或购买本服务相关付费内容前，请您仔细阅读并充分理解本协议的全部内容。您一旦访问或使用本服务，即视为您已阅读、理解并同意接受本协议全部条款的约束。如您不同意本协议任何内容，请立即停止访问或使用本服务。'] },
      { title: '1. 服务性质', paragraphs: ['VAID 是一项用于数字内容展示、记录辅助、验证辅助及相关服务支持的在线服务，主要用于帮助用户生成数字证书、展示相关信息、提供验证结果及辅助证明材料。', '本服务仅提供技术性与信息展示性支持，不构成法律意义上的版权登记、权属确认、公证、司法认证、行政审批或任何政府机关、司法机关、仲裁机构、登记机构的官方背书或保证。', '本服务生成、展示或提供的数字证书、验证信息及相关材料，仅可作为用户进行说明、展示或辅助举证的参考材料，不当然等同于任何法定权利证明文件，也不当然产生对权属、原创性、合法性或真实性的最终认定效力。'] },
      { title: '2. 用户承诺', paragraphs: ['您在使用本服务时承诺并保证：'], items: ['您对上传、提交、生成、展示或以其他方式使用的内容享有合法权利，或已获得合法、充分、有效的授权；', '您上传或使用的内容不侵犯任何第三方的著作权、商标权、专利权、肖像权、名誉权、隐私权、个人信息权益或其他合法权益；', '您不会利用本服务上传、发布、传播、存储或展示任何违法违规、侵权、虚假、欺诈、侮辱诽谤、淫秽色情、暴力恐怖、歧视骚扰、危害未成年人身心健康或其他不适宜内容；', '您不会利用本服务从事任何违反法律法规、社会公序良俗或侵犯他人合法权益的行为；', '您不会通过任何方式干扰、破坏、攻击、逆向利用或不当使用本服务及其相关系统、页面、接口、流程或规则。'] },
      { paragraphs: ['如因您的上传内容、使用行为或其他与您相关的原因引发任何争议、投诉、举报、索赔、行政处罚、司法程序或其他法律责任，均由您自行承担；因此给 VAID 或任何第三方造成损失的，您应依法承担赔偿责任。'] },
      { title: '3. 服务内容', paragraphs: ['本服务可能向您提供以下内容或功能：'], items: ['上传图片并生成 VAID 数字证书及相关展示内容；', '生成与内容对应的验证信息、查询结果及辅助展示页面；', '提供在线验证、记录展示及相关辅助材料下载；', '提供订单管理、购买次数管理、激活码发放与使用支持；', '提供与上述服务相关的页面展示、技术支持与客户服务。'] },
      { paragraphs: ['本服务有权根据业务发展、运营安排、用户体验优化、技术升级、合规要求或其他合理需要，对服务内容、功能模块、页面设计、交付形式、使用规则、计费方式或服务流程进行调整、中断、限制、变更、升级或下线，但将尽合理努力保持主要服务的持续可用。'] },
      { title: '4. 数字证书与验证信息', paragraphs: ['您理解并同意：'], items: ['本服务生成的数字证书主要用于内容展示、记录说明及辅助证明；', '本服务展示的验证信息、查询结果、辅助材料或相关页面，仅用于帮助用户说明相关内容的生成、展示或记录情况；', '本服务提供的在线验证页、链接、二维码、查询结果或下载内容，仅属于辅助校验和辅助说明工具，不当然构成对相关内容权属、真实性、原创性、合法性或有效性的最终证明；', '本服务不保证任何第三方机构、平台、法院、仲裁机构、行政机关或其他主体必然认可、采信或接受本服务生成或展示的任何材料。'] },
      { paragraphs: ['您应自行妥善保存与使用本服务相关的原始文件、订单信息、数字证书、验证信息、下载文件及其他必要材料。如因您未妥善保存导致后续无法验证、无法展示、无法举证或权益受损，相关后果由您自行承担。'] },
      { title: '5. 支付与退款', paragraphs: ['如本服务提供付费功能，您应在购买前仔细确认套餐内容、价格、使用规则及适用范围。', '您同意：'], items: ['支付成功后，系统将根据订单向您发放相应权益或额度；', '已发放且可正常使用的额度或激活码，原则上不支持退款；', '如支付成功但未收到额度或激活码，您可通过网站页面公布的“联系我们”方式联系客服处理；', '如因本服务系统原因导致额度未到账或激活码无法正常使用，经客服核实后，本服务将为您补发或作合理处理；', '已消费的部分视为已实际使用，仅就未消费部分进行补发或其他合理处理；', '因用户填写错误、保管不善、转交他人、泄露激活码或其他非因本服务原因造成的损失，由用户自行承担；', '如因支付渠道、网络故障、第三方平台异常或其他非本服务可合理控制的原因导致支付延迟、状态不同步或短时异常，本服务将在合理范围内协助核查处理，但不对超出合理控制范围的部分承担责任。'] },
      { title: '6. 访问控制', paragraphs: ['本服务可能基于订单信息、激活码、访问凭证、设备环境、缓存信息或其他必要方式进行服务校验、权益识别、次数管理及安全控制。', '您理解并同意：'], items: ['前述信息仅用于实现服务交付、订单关联、使用管理、安全保障及体验优化；', '上述识别信息不当然等同于对用户真实身份的认证；', '您应妥善保管与订单、激活码或其他访问凭证相关的信息；', '因您自行泄露、转让、共享、遗失或保管不善而造成的任何损失，由您自行承担。'] },
      { title: '7. 第三方服务', paragraphs: ['本服务可能依赖第三方支付、云存储、数据库、网络服务、基础设施服务或其他第三方服务支持。', '因第三方服务的故障、延迟、中断、限制、调整、升级、政策变化或其他非 VAID 可合理控制的原因，导致本服务部分或全部功能受到影响的，在法律允许范围内，VAID 对超出合理控制范围的后果不承担责任，但会尽合理努力协助处理或恢复。'] },
      { title: '8. 知识产权', paragraphs: ['除用户依法享有权利的上传内容外，本服务中的商标、标识、名称、界面设计、页面布局、文案、图片、程序代码、结构安排、数据整理、服务规则及其他相关内容的知识产权，均归 VAID 或相关权利人所有。', '未经 VAID 或相关权利人事先书面许可，任何人不得以任何方式对本服务相关内容进行复制、传播、修改、改编、汇编、翻译、出租、出售、反向工程、反向编译、反汇编或其他不当使用。'] },
      { title: '9. 免责声明', paragraphs: ['在法律允许的最大范围内，本服务按“现状”和“可提供”状态向您提供。VAID 不对以下事项作出任何明示或默示保证：'], items: ['本服务将完全无错误、无中断、无延迟、无漏洞或永久可用；', '本服务生成或展示的内容一定会被任何第三方采信；', '本服务提供的数字证书、验证信息或辅助材料可以替代法定程序；', '用户上传内容当然具有原创性、合法性、完整性、真实性或可确权性；', '用户通过本服务获得的结果一定符合其特定用途或预期。'] },
      { paragraphs: ['因不可抗力、系统维护、网络故障、黑客攻击、病毒侵害、第三方服务异常、政策变化、监管要求或其他不可预见、不可避免、不可控制的原因导致的损失，VAID 不承担超出法律规定范围的责任。'] },
      { title: '10. 协议变更', paragraphs: ['VAID 有权根据业务需要、运营安排、法律法规要求或合规管理要求，对本协议内容进行修改或更新。', '如本协议发生重大变更，VAID 将通过网站公告、页面提示或其他合理方式进行通知。变更后的协议一经公布或在公告载明的生效日期起生效。您在协议更新后继续访问或使用本服务的，视为您已接受更新后的协议内容。'] },
      { title: '11. 法律适用与争议解决', paragraphs: ['本协议的订立、效力、解释、履行及争议解决，均适用中华人民共和国法律。', '如因本协议或本服务引起任何争议，双方应首先友好协商解决；协商不成的，任何一方均有权向 VAID Company 所在地有管辖权的人民法院提起诉讼。'] },
      { title: '12. 其他', paragraphs: ['如本协议任何条款被认定为无效、违法或不可执行，不影响本协议其他条款的有效性和可执行性。', '本协议标题仅为阅读方便而设，不影响条款含义解释。', '本协议未尽事宜，按法律法规规定及 VAID 相关页面规则执行；如相关页面规则与本协议存在冲突，以具体场景下另行明确说明的规则为准，但法律法规另有规定的除外。'] }
    ]
  },
  ja: {
    back: 'ホームへ戻る',
    title: '利用規約',
    effectiveDate: '施行日：2026年3月31日',
    operator: '運営者：VAID Company',
    siteName: 'サイト名：VAID',
    sections: [
      { paragraphs: ['VAID（以下「本サービス」）へようこそ。本サービスは VAID Company により運営・提供されます。', '本サービスへのアクセス、登録、利用、または有料コンテンツの購入前に、本規約をよくお読みください。本サービスを利用した場合、本規約を読み、理解し、すべての条項に同意したものとみなされます。同意しない場合は、直ちに利用を停止してください。'] },
      { title: '1. サービスの性質', paragraphs: ['VAID は、デジタルコンテンツの表示、記録補助、検証補助および関連サポートを提供するオンラインサービスであり、デジタル証明書の生成、関連情報の表示、検証結果および補助資料の提供を目的とします。', '本サービスは技術的および情報表示上の支援のみを提供し、著作権登録、権利確認、公証、司法認証、行政承認、または政府機関・司法機関・仲裁機関・登録機関による公式な保証や承認を構成するものではありません。', '本サービスが生成・表示・提供するデジタル証明書、検証情報および関連資料は、説明、表示、補助的証拠としての参考資料にすぎず、法的な権利証明、権利帰属、独自性、合法性または真実性の最終判断を当然に生じさせるものではありません。'] },
      { title: '2. ユーザーの表明と保証', paragraphs: ['本サービスの利用にあたり、お客様は以下を表明し保証します。'], items: ['アップロード、送信、生成、表示または利用するコンテンツについて、適法な権利または有効な許諾を有していること。', '利用コンテンツが第三者の著作権、商標権、特許権、肖像権、名誉権、プライバシー権、個人情報に関する権利その他の法的権利を侵害しないこと。', '違法、権利侵害、虚偽、詐欺、名誉毀損、わいせつ、暴力、テロ、差別、嫌がらせ、未成年者に有害または不適切なコンテンツをアップロード、公開、送信、保存、表示しないこと。', '法令、公序良俗、または他者の権利を侵害する行為に本サービスを利用しないこと。', '本サービス、関連システム、ページ、インターフェース、手順、規則を妨害、破壊、攻撃、逆利用、または不正利用しないこと。'] },
      { paragraphs: ['お客様のコンテンツまたは利用行為に起因する紛争、苦情、通報、請求、行政処分、司法手続または法的責任は、お客様自身が負担します。VAID または第三者に損害が生じた場合、お客様は法令に従い賠償責任を負います。'] },
      { title: '3. サービス内容', paragraphs: ['本サービスは以下の内容または機能を提供する場合があります。'], items: ['画像をアップロードし、VAIDデジタル証明書および関連表示内容を生成する機能。', 'コンテンツに対応する検証情報、検索結果、補助表示ページの生成。', 'オンライン検証、記録表示、関連補助資料のダウンロード。', '注文管理、利用回数管理、アクティベーションコードの発行および利用サポート。', '上記に関連するページ表示、技術サポート、カスタマーサービス。'] },
      { paragraphs: ['本サービスは、事業展開、運営上の都合、ユーザー体験の改善、技術アップグレード、法令遵守その他合理的な必要に応じ、サービス内容、機能、ページ設計、提供形式、利用規則、料金方式または手順を調整、中断、制限、変更、アップグレードまたは終了することがあります。ただし、主要サービスの継続的な提供に合理的な努力を払います。'] },
      { title: '4. デジタル証明書と検証情報', paragraphs: ['お客様は以下を理解し同意します。'], items: ['本サービスが生成するデジタル証明書は、主にコンテンツ表示、記録説明、補助的証明を目的とします。', '検証情報、検索結果、補助資料、関連ページは、生成、表示、記録状況の説明を補助するためのものです。', 'オンライン検証ページ、リンク、QRコード、検索結果、ダウンロード内容は補助的な確認・説明ツールであり、権利帰属、真実性、独自性、合法性、有効性の最終証明を当然に構成するものではありません。', '本サービスは、第三者機関、プラットフォーム、裁判所、仲裁機関、行政機関その他の主体が、本サービスにより生成または表示された資料を必ず承認、採用、受理することを保証しません。'] },
      { paragraphs: ['お客様は、原本ファイル、注文情報、デジタル証明書、検証情報、ダウンロードファイルその他必要な資料を適切に保存する必要があります。保存不備により後日検証、表示、立証または権益保護ができない場合、その結果はお客様が負担します。'] },
      { title: '5. 支払いと返金', paragraphs: ['有料機能が提供される場合、購入前にプラン内容、価格、利用規則および適用範囲を確認してください。', 'お客様は以下に同意します。'], items: ['支払い完了後、システムは注文に応じた権益または利用回数を付与します。', '正常に利用可能な利用回数またはアクティベーションコードは、原則として返金対象外です。', '支払い完了後に利用回数またはコードが届かない場合、サイトの「お問い合わせ」からご連絡ください。', '本サービスのシステム原因により利用回数が反映されない、またはコードが正常に利用できない場合、確認後に再発行または合理的な対応を行います。', '消費済み部分は実際に利用済みとみなし、未消費部分についてのみ再発行または合理的対応を行います。', '入力ミス、管理不備、第三者への譲渡、コード漏洩その他本サービスの責めに帰さない理由による損失は、お客様が負担します。', '決済チャネル、ネットワーク障害、第三者プラットフォーム異常その他本サービスが合理的に管理できない理由による支払い遅延、状態不一致、一時的障害について、本サービスは合理的範囲で調査に協力しますが、管理範囲外の部分について責任を負いません。'] },
      { title: '6. アクセス制御', paragraphs: ['本サービスは、注文情報、アクティベーションコード、アクセス資格情報、デバイス環境、キャッシュ情報その他必要な手段に基づき、サービス確認、権益識別、利用回数管理およびセキュリティ制御を行う場合があります。', 'お客様は以下を理解し同意します。'], items: ['これらの情報はサービス提供、注文関連付け、利用管理、セキュリティ、体験改善のためにのみ使用されます。', 'これらの識別情報は、必ずしもユーザーの実名認証を意味しません。', '注文、アクティベーションコード、その他アクセス資格情報を適切に管理してください。', 'お客様による漏洩、譲渡、共有、紛失、管理不備に起因する損失はお客様が負担します。'] },
      { title: '7. 第三者サービス', paragraphs: ['本サービスは、第三者の決済、クラウドストレージ、データベース、ネットワーク、インフラその他のサービスに依存する場合があります。', '第三者サービスの障害、遅延、中断、制限、調整、アップグレード、方針変更その他 VAID が合理的に管理できない理由により本サービスの一部または全部が影響を受けた場合、法令で認められる範囲で VAID は管理範囲外の結果について責任を負いません。ただし、合理的な努力により対応または復旧に協力します。'] },
      { title: '8. 知的財産権', paragraphs: ['ユーザーが適法な権利を有するアップロードコンテンツを除き、本サービス上の商標、ロゴ、名称、インターフェース、ページレイアウト、文章、画像、コード、構造、データ整理、サービス規則その他関連内容の知的財産権は、VAID または関連権利者に帰属します。', 'VAID または関連権利者の事前の書面による許可なく、本サービス関連内容を複製、配布、変更、翻案、編集、翻訳、貸与、販売、リバースエンジニアリング、逆コンパイル、逆アセンブル、その他不正に利用してはなりません。'] },
      { title: '9. 免責事項', paragraphs: ['法令で認められる最大限の範囲で、本サービスは「現状有姿」および「提供可能な範囲」で提供されます。VAID は以下を明示または黙示に保証しません。'], items: ['本サービスが完全にエラーなく、中断なく、遅延なく、脆弱性なく、永続的に利用可能であること。', '本サービスが生成または表示する内容が第三者に必ず採用されること。', 'デジタル証明書、検証情報、補助資料が法定手続に代替できること。', 'ユーザーアップロード内容が当然に独自、合法、完全、真実、または権利確認可能であること。', '本サービスの結果がお客様の特定目的または期待に適合すること。'] },
      { paragraphs: ['不可抗力、システム保守、ネットワーク障害、ハッカー攻撃、ウイルス、第三者サービス異常、方針変更、規制要請、その他予見不能・回避不能・制御不能な原因による損失について、VAID は法令で定められる範囲を超えて責任を負いません。'] },
      { title: '10. 規約の変更', paragraphs: ['VAID は、事業上の必要、運営上の都合、法令上の要請、コンプライアンス上の必要に応じ、本規約を変更または更新することがあります。', '重大な変更がある場合、VAID はウェブサイト公告、ページ表示、その他合理的な方法で通知します。変更後の規約は公表時または指定された施行日に効力を生じます。更新後も本サービスを利用する場合、更新後の規約に同意したものとみなされます。'] },
      { title: '11. 準拠法および紛争解決', paragraphs: ['本規約の成立、効力、解釈、履行および紛争解決には、中華人民共和国法が適用されます。', '本規約または本サービスに起因する紛争について、当事者はまず友好的に協議して解決するものとします。協議で解決しない場合、いずれの当事者も VAID Company 所在地を管轄する人民法院に訴訟を提起できます。'] },
      { title: '12. その他', paragraphs: ['本規約のいずれかの条項が無効、違法または執行不能と判断された場合でも、他の条項の有効性および執行可能性には影響しません。', '見出しは便宜上のものであり、条項の解釈に影響しません。', '本規約に定めのない事項は、法令および VAID の関連ページ規則に従います。関連ページ規則と本規約が矛盾する場合、具体的な場面で明示された規則を優先します。ただし法令に別段の定めがある場合を除きます。'] }
    ]
  }
};

function getLegalLanguage(language: string | undefined): LegalLanguage {
  if (language?.startsWith('ja')) return 'ja';
  if (language?.startsWith('zh')) return 'zh';
  return 'en';
}

export function TermsPage() {
  const navigate = useNavigate();
  const { i18n } = useTranslation();
  const content = termsContent[getLegalLanguage(i18n.resolvedLanguage ?? i18n.language)];

  return (
    <div className="min-h-screen bg-[#171717] text-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <button onClick={() => navigate('/')} className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors mb-10">
          <ArrowLeft className="w-4 h-4" />
          {content.back}
        </button>

        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 bg-blue-500/10 border border-blue-500/30 rounded-lg flex items-center justify-center">
            <FileCheck className="w-5 h-5 text-blue-400" />
          </div>
          <h1 className="text-3xl font-bold">{content.title}</h1>
        </div>

        <p className="text-slate-400 text-sm mb-10">{content.effectiveDate}</p>

        <div className="space-y-10 text-slate-300 leading-relaxed">
          {content.sections.map((section, index) => (
            <section key={index}>
              {section.title && <h2 className="text-xl font-semibold text-white mb-4">{section.title}</h2>}
              {section.paragraphs?.map((paragraph) => <p key={paragraph} className="mb-3 last:mb-0">{paragraph}</p>)}
              {section.items && (
                <ul className="list-disc list-inside space-y-2 text-slate-400 ml-2 mt-2">
                  {section.items.map((item) => <li key={item}>{item}</li>)}
                </ul>
              )}
            </section>
          ))}
        </div>

        <div className="mt-12 pt-8 border-t border-slate-800 text-center text-slate-600 text-sm">
          <p>{content.operator}</p>
          <p className="mt-2">{content.siteName}</p>
        </div>
      </div>
    </div>
  );
}
