/*
  # V-ID License Keys Table

  1. New Tables
    - `license_keys`
      - `id` (uuid, primary key) - Unique identifier
      - `key` (text, unique) - License key string
      - `pack_size` (int) - Number of certificates in pack (1, 5, or 10)
      - `used` (boolean) - Whether the key has been activated
      - `activated_at` (timestamptz) - When the key was activated
      - `created_at` (timestamptz) - When the key was created
  
  2. Security
    - Enable RLS on `license_keys` table
    - Add policy for public to check key validity (but not list all keys)
    - Add policy for authenticated admins to manage keys

  3. Important Notes
    - Keys are validated on the client side for now
    - In production, this should be validated via Edge Function
    - Keys should be generated by admin panel (not included in this migration)
*/

CREATE TABLE IF NOT EXISTS license_keys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  pack_size int NOT NULL CHECK (pack_size IN (1, 5, 10)),
  used boolean DEFAULT false,
  activated_at timestamptz,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE license_keys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can check if a specific key exists"
  ON license_keys
  FOR SELECT
  USING (true);

CREATE POLICY "Only authenticated users can mark keys as used"
  ON license_keys
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');
