import { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { supabase } from '../utils/supabase';
import { calculateSHA256 } from '../utils/sha256';
import { consumeGenerationReady } from '../utils/licenseManager';
import { CERTIFICATE_CANVAS_WIDTH, formatCertificateIssuedDate, renderCertificateCanvas } from '../utils/certificateCanvas';

const ASSET_BASE_URL = import.meta.env.BASE_URL || '/';

function resolveAssetUrl(path: string): string {
  return `${ASSET_BASE_URL}${path.replace(/^\/+/, '')}`;
}

interface FormData {
  name: string;
  status: string;
  issuedDate: string;
  serialId: string;
  description: string;
  qrContent: string;
  qrToken: string;
  qrRecord: string;
}

interface ArchiveCertificateMetadata {
  createdAt?: string;
}

interface EvidenceMaterialRecord {
  file_name: string;
  material_type: string;
  file_size_bytes: number;
  sha256_hash: string;
  created_at: string;
}

interface EvidenceManifest {
  materials: EvidenceMaterialRecord[];
  manifestText: string;
  manifestHash: string;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatDateTime(value?: string): string {
  if (!value) return 'Not available';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

type DownloadLanguage = 'en' | 'zh' | 'ja';

function getDownloadLanguage(language?: string): DownloadLanguage {
  if (language?.startsWith('zh')) return 'zh';
  if (language?.startsWith('ja')) return 'ja';
  return 'en';
}

function getCardCopy() {
  return {
    status: 'VERIFIED',
    description: 'THIS DOCUMENT PROVIDES VERIFIABLE EVIDENCE OF A UNIQUE DIGITAL IDENTITY RECORDED BY VAID.',
    canvas: {
      nameLabel: 'NAME:',
      statusLabel: 'STATUS:',
      createdLabel: 'CREATED:',
      recordIdLabel: 'RECORD ID:',
      proofLabel: 'PROOF:',
      proofValue: 'Blockchain sealed',
    },
  };
}

function getLocalizedBundleNames(language: DownloadLanguage) {
  if (language === 'zh') {
    return {
      identityCard: 'VAID_数字身份卡片.png',
      archiveCertificate: 'VAID_数字身份存档证书.pdf',
      verificationGuide: 'VAID_证明验证说明.txt',
    };
  }

  if (language === 'ja') {
    return {
      identityCard: 'VAID_デジタルアイデンティティカード.png',
      archiveCertificate: 'VAID_デジタルアイデンティティアーカイブ証明書.pdf',
      verificationGuide: 'VAID_証明確認ガイド.txt',
    };
  }

  return {
    identityCard: 'VAID_Digital_Identity_Card.png',
    archiveCertificate: 'VAID_Digital_Identity_Archive_Certificate.pdf',
    verificationGuide: 'VAID_Proof_Verification_Guide.txt',
  };
}

function getArchiveCertificateCopy(language: DownloadLanguage) {
  if (language === 'zh') {
    return {
      htmlLang: 'zh-CN',
      title: 'VAID 数字身份存档证书',
      subtitle: '本证书记录与已下载 VAID 数字身份卡片相关联的数字身份存档信息。',
      sectionTitle: '存档记录',
      statementTitle: '证书说明',
      preservationTitle: '保存说明',
      generatedBy: '由 VAID Protocol 生成',
      fields: {
        recordId: '档案编号',
        characterName: '角色名称',
        createdTime: '创建时间',
        sha256Hash: '图片哈希值',
        publicVerificationUrl: '公开验证链接',
        privateEvidenceMaterials: '私有证据材料',
        evidenceManifestHash: '证据清单哈希值',
      },
      manifestTitle: '私有证据材料清单',
      manifestSubtitle: '本页列出与该 VAID 记录相关联的私有创作证明材料元数据。原始材料文件不包含在本 PDF 中，应由用户自行长期保存。',
      manifestEmpty: '未登记私有证据材料。',
      manifestColumns: {
        fileName: '文件名',
        type: '类型',
        size: '大小',
        sha256Hash: 'SHA-256',
        registeredAt: '登记时间',
      },
      statement: '本文件为 VAID 生成的数字身份存档证书，用于记录说明和辅助证明。它记录档案编号、创建信息、数字指纹和公开验证链接。本文件不等同于版权登记、公证、司法认证、行政确权或任何政府机关出具的权属证明。',
      preservation: '请将本 PDF 证书、数字身份卡片、公开验证链接、原始文件和创作过程材料一并保存。为了隐私安全，VAID 不会保存你的源文件。如发生争议，应结合原始文件、创作过程记录、公开验证页和其他相关证据共同使用。',
    };
  }

  if (language === 'ja') {
    return {
      htmlLang: 'ja',
      title: 'VAID デジタルアイデンティティアーカイブ証明書',
      subtitle: 'この証明書は、ダウンロードされた VAID デジタルアイデンティティカードに関連するアーカイブ記録を要約するものです。',
      sectionTitle: 'アーカイブ記録',
      statementTitle: '証明書の声明',
      preservationTitle: '保存上の注意',
      generatedBy: 'Generated by VAID Protocol',
      fields: {
        recordId: 'Record ID',
        characterName: 'Character Name',
        createdTime: 'Created Time',
        sha256Hash: 'SHA-256 Hash',
        publicVerificationUrl: 'Public Verification URL',
        privateEvidenceMaterials: 'Private Evidence Materials',
        evidenceManifestHash: 'Evidence Manifest Hash',
      },
      manifestTitle: 'プライベート証拠資料一覧',
      manifestSubtitle: 'このページは、この VAID レコードに関連する非公開の制作証明資料メタデータを示します。原本ファイルはこの PDF には含まれず、ユーザー自身で長期保存してください。',
      manifestEmpty: 'No private evidence materials registered.',
      manifestColumns: {
        fileName: 'File Name',
        type: 'Type',
        size: 'Size',
        sha256Hash: 'SHA-256',
        registeredAt: 'Registered At',
      },
      statement: 'この文書は、記録説明および補助証拠のために VAID が生成したデジタルアイデンティティアーカイブ証明書です。アーカイブ識別子、作成情報、デジタルフィンガープリント、公開検証リンクを記録します。著作権登録、公証、司法認証、行政上の権利確認、または政府機関による所有権証明に代わるものではありません。',
      preservation: 'この PDF 証明書、デジタルアイデンティティカード、公開検証リンク、原本ファイル、制作過程の資料を一緒に保存してください。プライバシー保護のため、VAID はあなたの原本ファイルを保存しません。紛争が発生した場合は、原本ファイル、制作過程の記録、公開検証ページ、その他の関連証拠とあわせて使用してください。',
    };
  }

  return {
    htmlLang: 'en',
    title: 'VAID Digital Identity Archive Certificate',
    subtitle: 'This certificate summarizes the VAID archive record associated with the downloaded digital identity card.',
    sectionTitle: 'Archive Record',
    statementTitle: 'Certificate Statement',
    preservationTitle: 'Preservation Note',
    generatedBy: 'Generated by VAID Protocol',
    fields: {
      recordId: 'Record ID',
      characterName: 'Character Name',
      createdTime: 'Created Time',
      sha256Hash: 'SHA-256 Hash',
      publicVerificationUrl: 'Public Verification URL',
      privateEvidenceMaterials: 'Private Evidence Materials',
      evidenceManifestHash: 'Evidence Manifest Hash',
    },
    manifestTitle: 'Private Evidence Manifest',
    manifestSubtitle: 'This page lists private creation proof material metadata associated with this VAID record. Original material files are not embedded in this PDF and should be retained by the user.',
    manifestEmpty: 'No private evidence materials registered.',
    manifestColumns: {
      fileName: 'File Name',
      type: 'Type',
      size: 'Size',
      sha256Hash: 'SHA-256',
      registeredAt: 'Registered At',
    },
    statement: 'This document is a VAID-generated digital identity archive certificate for record explanation and auxiliary evidence. It records the archive identifier, creation information, digital fingerprint, and public verification link. It does not replace copyright registration, notarization, judicial certification, administrative confirmation, or any government-issued ownership certificate.',
    preservation: 'Keep this PDF certificate, the digital identity card, the public verification link, original files, and creation-process materials together. For privacy and security, VAID does not store your source files. If a dispute occurs, use them together with the original files, creation records, public verification page, and other relevant evidence.',
  };
}

function formatFileSize(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return 'Not available';
  const units = ['B', 'KB', 'MB', 'GB'];
  let value = bytes;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }
  return `${value.toFixed(unitIndex === 0 ? 0 : 2)} ${units[unitIndex]}`;
}

function buildEvidenceManifestText(form: FormData, materials: EvidenceMaterialRecord[]): string {
  return [
    'VAID Private Evidence Manifest',
    `Record ID: ${form.serialId}`,
    `Material Count: ${materials.length}`,
    ...materials.map((material, index) => [
      `Material ${index + 1}`,
      `File Name: ${material.file_name}`,
      `Type: ${material.material_type}`,
      `MIME/Size: ${formatFileSize(Number(material.file_size_bytes))}`,
      `SHA-256: ${material.sha256_hash}`,
      `Registered At: ${formatDateTime(material.created_at)}`,
    ].join('\n')),
  ].join('\n\n');
}

async function buildEvidenceManifest(
  form: FormData,
  materials: EvidenceMaterialRecord[]
): Promise<EvidenceManifest | null> {
  if (materials.length === 0) return null;
  const sortedMaterials = [...materials].sort((left, right) => {
    const hashCompare = left.sha256_hash.localeCompare(right.sha256_hash);
    if (hashCompare !== 0) return hashCompare;
    return left.file_name.localeCompare(right.file_name);
  });
  const manifestText = buildEvidenceManifestText(form, sortedMaterials);
  return {
    materials: sortedMaterials,
    manifestText,
    manifestHash: await calculateSHA256(manifestText),
  };
}

function buildArchiveCertificateHtml(
  form: FormData,
  sha256Hash: string,
  verifyUrl: string,
  metadata: ArchiveCertificateMetadata,
  language: DownloadLanguage,
  evidenceManifest: EvidenceManifest | null
): string {
  const copy = getArchiveCertificateCopy(language);
  const fields = [
    { label: copy.fields.recordId, value: form.serialId },
    { label: copy.fields.characterName, value: form.name },
    { label: copy.fields.createdTime, value: metadata.createdAt ? formatDateTime(metadata.createdAt) : form.issuedDate },
    { label: copy.fields.publicVerificationUrl, value: verifyUrl },
    { label: copy.fields.sha256Hash, value: sha256Hash || 'Not available', isFingerprint: true },
    ...(evidenceManifest ? [
      { label: copy.fields.privateEvidenceMaterials, value: String(evidenceManifest.materials.length) },
      { label: copy.fields.evidenceManifestHash, value: evidenceManifest.manifestHash, isFingerprint: true },
    ] : []),
  ];

  return `<!doctype html>
<html lang="${copy.htmlLang}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(copy.title)} - ${escapeHtml(form.serialId)}</title>
  <style>
    * { box-sizing: border-box; }
    html {
      background: #ffffff;
      color-scheme: light only;
    }
    body {
      margin: 0;
      background: #ffffff;
      color: #172033;
      color-scheme: light only;
      font-family: "Avenir Next", "Segoe UI", "Noto Sans SC", "Hiragino Sans", Arial, sans-serif;
      line-height: 1.55;
    }
    .page, .page * {
      color-scheme: light only;
      forced-color-adjust: none;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .page {
      width: 794px;
      min-height: 1123px;
      margin: 0 auto;
      background: #ffffff;
      background-color: #ffffff;
      color: #172033;
      padding: 92px 84px;
      border: 1px solid #c8d3df;
      position: relative;
    }
    .border {
      display: none;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      gap: 24px;
      border-bottom: 2px solid #d8e1ea;
      padding-bottom: 22px;
    }
    .brand {
      font-size: 34px;
      letter-spacing: 0.08em;
      font-weight: 700;
      color: #0f2742;
    }
    h1 {
      margin: 38px 0 10px;
      font-size: 28px;
      color: #0f2742;
      text-align: center;
      letter-spacing: 0;
    }
    .subtitle {
      margin: 0 auto 34px;
      max-width: 580px;
      color: #5a6878;
      text-align: center;
      font-size: 14px;
    }
    .section-title {
      margin: 30px 0 12px;
      color: #183655;
      font-size: 15px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      border: 1px solid #d9e2eb;
      background: #ffffff;
    }
    th, td {
      border-bottom: 1px solid #e4ebf2;
      padding: 13px 15px;
      vertical-align: top;
      font-size: 13px;
    }
    th {
      width: 34%;
      color: #58687a;
      text-align: left;
      font-weight: 700;
      background: #f4f7fa;
    }
    td {
      color: #172033;
      word-break: break-word;
      font-family: "Segoe UI", Arial, sans-serif;
    }
    .fingerprint {
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      font-size: 11px;
      line-height: 1.7;
    }
    .statement {
      border: 1px solid #d9e2eb;
      background: #f7fafc;
      background-color: #f7fafc;
      padding: 18px 20px;
      color: #38485a;
      font-size: 13px;
    }
    .statement p {
      margin: 0;
    }
    .statement p + p {
      margin-top: 12px;
    }
    .manifest-page h1 {
      margin-top: 34px;
    }
    .manifest-summary {
      display: grid;
      grid-template-columns: 1fr;
      gap: 10px;
      margin: 24px 0;
      padding: 16px 18px;
      border: 1px solid #d9e2eb;
      background: #f7fafc;
      color: #38485a;
      font-size: 12px;
    }
    .manifest-list {
      display: grid;
      gap: 12px;
    }
    .manifest-item {
      border: 1px solid #d9e2eb;
      background: #ffffff;
      padding: 14px 16px;
      font-size: 11px;
      color: #38485a;
    }
    .manifest-item-title {
      color: #172033;
      font-weight: 700;
      font-size: 12px;
      margin-bottom: 8px;
      word-break: break-word;
    }
    .manifest-row {
      display: grid;
      grid-template-columns: 104px 1fr;
      gap: 10px;
      margin-top: 5px;
    }
    .manifest-label {
      color: #6c7b8d;
      font-weight: 700;
    }
    .manifest-value {
      color: #172033;
      word-break: break-word;
    }
    .footer {
      position: absolute;
      left: 84px;
      right: 84px;
      bottom: 76px;
      border-top: 0;
      padding-top: 14px;
      color: #6c7b8d;
      font-size: 11px;
      display: flex;
      justify-content: space-between;
      gap: 20px;
    }
  </style>
</head>
<body>
  <main class="page">
    <div class="border"></div>
    <header class="header">
      <div class="brand">VAID</div>
    </header>

    <h1>${escapeHtml(copy.title)}</h1>
    <p class="subtitle">
      ${escapeHtml(copy.subtitle)}
    </p>

    <div class="section-title">${escapeHtml(copy.sectionTitle)}</div>
    <table>
      <tbody>
        ${fields.map(({ label, value, isFingerprint }) => `
        <tr>
          <th>${escapeHtml(label)}</th>
          <td class="${isFingerprint ? 'fingerprint' : ''}">${escapeHtml(value)}</td>
        </tr>`).join('')}
      </tbody>
    </table>

    <div class="section-title">${escapeHtml(copy.statementTitle)}</div>
    <div class="statement">
      <p>${escapeHtml(copy.statement)}</p>
    </div>

    <div class="section-title">${escapeHtml(copy.preservationTitle)}</div>
    <div class="statement">
      <p>${escapeHtml(copy.preservation)}</p>
    </div>

    <footer class="footer">
      <span>${escapeHtml(copy.generatedBy)}</span>
      <span>${escapeHtml(form.serialId)}</span>
    </footer>
  </main>
  ${evidenceManifest ? `
  <main class="page manifest-page">
    <div class="border"></div>
    <header class="header">
      <div class="brand">VAID</div>
    </header>

    <h1>${escapeHtml(copy.manifestTitle)}</h1>
    <p class="subtitle">${escapeHtml(copy.manifestSubtitle)}</p>

    <div class="manifest-summary">
      <div><strong>${escapeHtml(copy.fields.privateEvidenceMaterials)}:</strong> ${evidenceManifest.materials.length}</div>
      <div><strong>${escapeHtml(copy.fields.evidenceManifestHash)}:</strong> <span class="fingerprint">${escapeHtml(evidenceManifest.manifestHash)}</span></div>
    </div>

    <div class="manifest-list">
      ${evidenceManifest.materials.map((material, index) => `
      <section class="manifest-item">
        <div class="manifest-item-title">${index + 1}. ${escapeHtml(material.file_name)}</div>
        <div class="manifest-row">
          <div class="manifest-label">${escapeHtml(copy.manifestColumns.type)}</div>
          <div class="manifest-value">${escapeHtml(material.material_type)}</div>
        </div>
        <div class="manifest-row">
          <div class="manifest-label">${escapeHtml(copy.manifestColumns.size)}</div>
          <div class="manifest-value">${escapeHtml(formatFileSize(Number(material.file_size_bytes)))}</div>
        </div>
        <div class="manifest-row">
          <div class="manifest-label">${escapeHtml(copy.manifestColumns.sha256Hash)}</div>
          <div class="manifest-value fingerprint">${escapeHtml(material.sha256_hash)}</div>
        </div>
        <div class="manifest-row">
          <div class="manifest-label">${escapeHtml(copy.manifestColumns.registeredAt)}</div>
          <div class="manifest-value">${escapeHtml(formatDateTime(material.created_at))}</div>
        </div>
      </section>`).join('')}
    </div>

    <footer class="footer">
      <span>${escapeHtml(copy.generatedBy)}</span>
      <span>${escapeHtml(form.serialId)}</span>
    </footer>
  </main>` : ''}
</body>
</html>`;
}

function getVerificationGuide(
  language: DownloadLanguage,
  form: FormData,
  sha256Hash: string,
  verifyUrl: string
): string {
  if (language === 'zh') {
    return `VAID 证明验证说明
====================

本下载包用于保存一份 VAID 数字身份记录的本地证明材料。

文件内容：
1. VAID_数字身份卡片.png
   用于展示和分享的数字身份卡片。
2. VAID_数字身份存档证书.pdf
   用于记录说明和辅助证明的正式 PDF 证书。
3. VAID_证明验证说明.txt
   本说明文件。
4. .ots 文件（如存在）
   时间戳证明文件。该文件仅在系统可提供时附带。

核心信息：
Character Name: ${form.name}
Record ID: ${form.serialId}
Created Time: ${form.issuedDate}
SHA-256 Hash: ${sha256Hash || 'Not available'}
Public Verification URL: ${verifyUrl}

如何验证：
1. 打开 Public Verification URL。
2. 对照公开验证页中的 Record ID、Character Name、Created Time 与本下载包是否一致。
3. 对照 SHA-256 Hash 是否一致。
4. 如下载包内包含 .ots 文件，请与本下载包一起保存。
5. 如果 PDF 证书包含 Private Evidence Manifest，请用您自行保存的原始证明材料重新计算 SHA-256，并与清单中的哈希值核对。
6. 原始文件、创作过程截图、录屏、提示词记录、平台记录等材料应由您自行长期保存。

重要说明：
VAID 证书和验证页是记录说明与辅助证明材料，不等同于版权登记、公证、司法认证、行政确权或任何政府机关出具的权属证明。如发生争议，应结合原始文件、创作过程材料、VAID 证书、公开验证页和其他相关证据共同使用。

© VAID Protocol
`;
  }

  if (language === 'ja') {
    return `VAID 証明確認ガイド
====================

このダウンロードパッケージは、VAID デジタルアイデンティティ記録のローカル証明資料を保存するためのものです。

ファイル内容：
1. VAID_デジタルアイデンティティカード.png
   表示および共有用のデジタルアイデンティティカードです。
2. VAID_デジタルアイデンティティアーカイブ証明書.pdf
   記録説明および補助証拠のための正式な PDF 証明書です。
3. VAID_証明確認ガイド.txt
   この説明ファイルです。
4. .ots ファイル（存在する場合）
   タイムスタンプ証明ファイルです。システムが提供可能な場合のみ同梱されます。

主要情報：
Character Name: ${form.name}
Record ID: ${form.serialId}
Created Time: ${form.issuedDate}
SHA-256 Hash: ${sha256Hash || 'Not available'}
Public Verification URL: ${verifyUrl}

確認方法：
1. Public Verification URL を開きます。
2. 公開検証ページの Record ID、Character Name、Created Time がこのパッケージと一致することを確認します。
3. SHA-256 Hash が一致することを確認します。
4. パッケージに .ots ファイルが含まれる場合は、一緒に保存してください。
5. PDF 証明書に Private Evidence Manifest が含まれる場合は、ご自身で保存した原本証明資料から SHA-256 を再計算し、一覧のハッシュ値と照合してください。
6. 原本ファイル、制作過程のスクリーンショット、画面録画、プロンプト記録、プラットフォーム記録などはご自身で長期保存してください。

重要事項：
VAID 証明書および検証ページは、記録説明と補助証拠のための資料であり、著作権登録、公証、司法認証、行政上の権利確認、または政府機関による所有権証明に代わるものではありません。紛争が発生した場合は、原本ファイル、制作過程資料、VAID 証明書、公開検証ページ、その他の関連証拠とあわせて使用してください。

© VAID Protocol
`;
  }

  return `VAID PROOF VERIFICATION GUIDE
=============================

This download package preserves local proof materials for one VAID digital identity record.

Package contents:
1. VAID_Digital_Identity_Card.png
   A digital identity card for display and sharing.
2. VAID_Digital_Identity_Archive_Certificate.pdf
   A formal PDF certificate for record explanation and auxiliary evidence.
3. VAID_Proof_Verification_Guide.txt
   This guide.
4. .ots file, if present
   A timestamp proof file included only when available.

Core information:
Character Name: ${form.name}
Record ID: ${form.serialId}
Created Time: ${form.issuedDate}
SHA-256 Hash: ${sha256Hash || 'Not available'}
Public Verification URL: ${verifyUrl}

How to verify:
1. Open the Public Verification URL.
2. Compare the Record ID, Character Name, and Created Time shown on the public verification page with this package.
3. Compare the SHA-256 Hash.
4. If this package includes an .ots file, keep it together with the package.
5. If the PDF certificate includes a Private Evidence Manifest, recompute SHA-256 from your retained original proof materials and compare it with the manifest hashes.
6. Keep original files, creation-process screenshots, screen recordings, prompt records, platform records, and related materials yourself.

Important note:
The VAID certificate and verification page are record explanation and auxiliary proof materials. They do not replace copyright registration, notarization, judicial certification, administrative confirmation, or any government-issued ownership certificate. If a dispute occurs, use them together with original files, creation-process materials, the VAID certificate, the public verification page, and other relevant evidence.

© VAID Protocol
`;
}

function buildJpegPdf(pages: Array<{ jpegBytes: ArrayBuffer; width: number; height: number }>): Blob {
  const pageWidth = 595.28;
  const pageHeight = 841.89;
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
  ];
  const pageObjectNumbers: number[] = [];

  pages.forEach((page, index) => {
    const pageObjectNumber = 3 + index * 3;
    const imageObjectNumber = pageObjectNumber + 1;
    const contentObjectNumber = pageObjectNumber + 2;
    pageObjectNumbers.push(pageObjectNumber);

    const scale = Math.min(pageWidth / page.width, pageHeight / page.height);
    const imageWidth = page.width * scale;
    const imageHeight = page.height * scale;
    const imageX = (pageWidth - imageWidth) / 2;
    const imageY = (pageHeight - imageHeight) / 2;
    const imageArray = new Uint8Array(page.jpegBytes);
    let imageBinary = '';
    for (let i = 0; i < imageArray.length; i += 0x8000) {
      imageBinary += String.fromCharCode(...imageArray.subarray(i, i + 0x8000));
    }
    const imageName = `Im${index}`;
    const contentStream = `q\n${imageWidth.toFixed(2)} 0 0 ${imageHeight.toFixed(2)} ${imageX.toFixed(2)} ${imageY.toFixed(2)} cm\n/${imageName} Do\nQ`;

    objects.push(
      `${pageObjectNumber} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /${imageName} ${imageObjectNumber} 0 R >> >> /Contents ${contentObjectNumber} 0 R >>\nendobj\n`,
      `${imageObjectNumber} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${imageBinary.length} >>\nstream\n${imageBinary}\nendstream\nendobj\n`,
      `${contentObjectNumber} 0 obj\n<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream\nendobj\n`
    );
  });

  objects.splice(
    1,
    0,
    `2 0 obj\n<< /Type /Pages /Kids [${pageObjectNumbers.map((objectNumber) => `${objectNumber} 0 R`).join(' ')}] /Count ${pageObjectNumbers.length} >>\nendobj\n`
  );

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  for (const object of objects) {
    offsets.push(pdf.length);
    pdf += object;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  const bytes = new Uint8Array(pdf.length);
  for (let i = 0; i < pdf.length; i += 1) {
    bytes[i] = pdf.charCodeAt(i) & 0xff;
  }

  return new Blob([bytes], { type: 'application/pdf' });
}

async function buildArchiveCertificatePdf(
  form: FormData,
  sha256Hash: string,
  verifyUrl: string,
  metadata: ArchiveCertificateMetadata,
  language: DownloadLanguage,
  evidenceManifest: EvidenceManifest | null
): Promise<Blob> {
  const html = buildArchiveCertificateHtml(form, sha256Hash, verifyUrl, metadata, language, evidenceManifest);
  const frame = document.createElement('iframe');
  frame.style.position = 'fixed';
  frame.style.left = '-10000px';
  frame.style.top = '0';
  frame.style.width = '794px';
  frame.style.height = '1123px';
  frame.style.border = '0';
  frame.style.backgroundColor = '#ffffff';
  frame.style.setProperty('color-scheme', 'light only');
  document.body.appendChild(frame);

  try {
    const frameDocument = frame.contentDocument;
    if (!frameDocument) throw new Error('Archive certificate frame unavailable');

    frameDocument.open();
    frameDocument.write(html);
    frameDocument.close();

    await new Promise<void>((resolve) => {
      window.requestAnimationFrame(() => window.requestAnimationFrame(() => resolve()));
    });
    await frameDocument.fonts?.ready.catch(() => undefined);

    const { default: html2canvas } = await import('html2canvas');
    const pageElements = Array.from(frameDocument.querySelectorAll('.page')) as HTMLElement[];
    if (pageElements.length === 0) throw new Error('Archive certificate page missing');

    const pdfPages = [];
    for (const page of pageElements) {
      const canvas = await html2canvas(page, {
        backgroundColor: '#ffffff',
        scale: 2,
        useCORS: true,
        logging: false,
        onclone: (clonedDocument) => {
          clonedDocument.documentElement.style.backgroundColor = '#ffffff';
          clonedDocument.documentElement.style.setProperty('color-scheme', 'light only');
          if (clonedDocument.body) {
            clonedDocument.body.style.backgroundColor = '#ffffff';
            clonedDocument.body.style.color = '#172033';
            clonedDocument.body.style.setProperty('color-scheme', 'light only');
          }
          clonedDocument.querySelectorAll<HTMLElement>('.page').forEach((clonedPage) => {
            clonedPage.style.backgroundColor = '#ffffff';
            clonedPage.style.color = '#172033';
            clonedPage.style.setProperty('color-scheme', 'light only');
          });
          clonedDocument.querySelectorAll<HTMLElement>('.footer').forEach((footer) => {
            footer.style.borderTop = '0';
          });
        },
      });
      const jpegBlob = await new Promise<Blob>((resolve, reject) => {
        canvas.toBlob((blob) => {
          if (blob) {
            resolve(blob);
          } else {
            reject(new Error('Archive certificate image export failed'));
          }
        }, 'image/jpeg', 0.95);
      });
      pdfPages.push({
        jpegBytes: await jpegBlob.arrayBuffer(),
        width: canvas.width,
        height: canvas.height,
      });
    }
    return buildJpegPdf(pdfPages);
  } finally {
    frame.remove();
  }
}

export function CardGenerator() {
  const { t, i18n } = useTranslation();
  const cardCopy = useMemo(() => getCardCopy(), []);
  const CARD_GENERATOR_SESSION_KEY = 'v-id-card-generator-session';
  const navigate = useNavigate();
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const siteOrigin = window.location.origin;

  const [form, setForm] = useState<FormData>({
    name: 'ELIZA REED',
    status: 'VERIFIED',
    issuedDate: '',
    serialId: '',
    description: 'THIS DOCUMENT PROVIDES VERIFIABLE EVIDENCE OF A UNIQUE DIGITAL IDENTITY RECORDED BY VAID.',
    qrContent: '',
    qrToken: 'ABGD',
    qrRecord: 'SECURE DATA PROOF',
  });

  const [sha256Hash, setSha256Hash] = useState<string>('');
  const [citizenId, setCitizenId] = useState<string>('');
  const [accessError, setAccessError] = useState<string | null>(null);

  const [bgImg, setBgImg] = useState<HTMLImageElement | null>(null);
  const [logoImg, setLogoImg] = useState<HTMLImageElement | null>(null);
  const [textureImg, setTextureImg] = useState<HTMLImageElement | null>(null);
  const [avatarImg, setAvatarImg] = useState<HTMLImageElement | null>(null);
  const [qrImg, setQrImg] = useState<HTMLImageElement | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  const generateSerialId = useCallback(() => {
    const now = Date.now();
    const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    const seed = `${now.toString(36)}${Math.floor(Math.random() * 0x1000000).toString(36)}`.toUpperCase();
    let code = '';

    for (let i = 0; i < 8; i += 1) {
      const charCode = seed.charCodeAt(i % seed.length) + now + i * 17;
      code += alphabet[charCode % alphabet.length];
    }

    const recordId = `V${code}`;
    return `${recordId.slice(0, 3)}-${recordId.slice(3, 6)}-${recordId.slice(6)}`;
  }, []);

  useEffect(() => {
    const initializeCard = async () => {
      const isLocalPreview = import.meta.env.DEV && new URLSearchParams(window.location.search).get('preview') === '1';
      const savedAvatar = isLocalPreview ? resolveAssetUrl('hero_figure.webp') : localStorage.getItem('vid_uploaded_avatar');
      const savedName = isLocalPreview ? 'Preview Character' : localStorage.getItem('vid_character_name');
      const creatorName = isLocalPreview ? 'VAID Preview' : localStorage.getItem('vid_creator_name');
      const hasCardSession = isLocalPreview || sessionStorage.getItem(CARD_GENERATOR_SESSION_KEY) === '1';

      if (!savedAvatar || !savedName || !creatorName) {
        sessionStorage.removeItem(CARD_GENERATOR_SESSION_KEY);
        setAccessError(t('cardGenerator.errors.missingData'));
        navigate('/', { replace: true });
        return;
      }

      if (!hasCardSession && !consumeGenerationReady()) {
        setAccessError(t('cardGenerator.errors.expiredSession'));
        navigate('/', { replace: true });
        return;
      }

      sessionStorage.setItem(CARD_GENERATOR_SESSION_KEY, '1');

      const issuedDate = formatCertificateIssuedDate(new Date(), 'en');

      setForm(prev => ({
        ...prev,
        name: savedName,
        status: cardCopy.status,
        issuedDate,
        description: cardCopy.description,
        serialId: 'Generating...',
      }));

      const serialId = generateSerialId();

      (async () => {
        try {
          if (isLocalPreview) {
            const hashValue = await calculateSHA256(`${savedName}:${creatorName}:${issuedDate}:${savedAvatar}`);
            setSha256Hash(hashValue);
            setCitizenId(serialId);
            setForm(prev => ({
              ...prev,
              serialId,
              qrContent: `${siteOrigin}/verify/${serialId}`,
            }));
            return;
          }

          const registeredFriendlyId = localStorage.getItem('vid_registered_friendly_id') || '';
          const registeredHash = localStorage.getItem('vid_registered_hash') || '';
          if (registeredFriendlyId && registeredHash) {
            setCitizenId(registeredFriendlyId);
            setSha256Hash(registeredHash);
            setForm(prev => ({
              ...prev,
              serialId: registeredFriendlyId,
              qrContent: `${siteOrigin}/verify/${registeredFriendlyId}`,
            }));
            return;
          }

          setAccessError(t('cardGenerator.errors.missingRegisteredId'));
        } catch (err) {
          console.error('Unexpected error:', err);
          setAccessError(t('cardGenerator.errors.initializationFailed'));
        }
      })();
    };

    initializeCard();
  }, [CARD_GENERATOR_SESSION_KEY, cardCopy.description, cardCopy.status, generateSerialId, navigate, siteOrigin, t]);

  const loadImage = useCallback((src: string, timeout = 10000): Promise<HTMLImageElement> => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      const timeoutId = window.setTimeout(() => {
        img.src = '';
        reject(new Error(`Image load timeout: ${src}`));
      }, timeout);
      img.onload = () => {
        window.clearTimeout(timeoutId);
        resolve(img);
      };
      img.onerror = () => {
        window.clearTimeout(timeoutId);
        reject(new Error(`Image load failed: ${src}`));
      };
      img.src = src;
    });
  }, []);

  useEffect(() => {
    const loadResources = async () => {
      const bgUrl = resolveAssetUrl('bg.jpg');
      const logoUrl = resolveAssetUrl('vaid_logo_mark.png');
      const textureUrl = resolveAssetUrl('grid_texture.png');

      const [bgResult, logoResult, textureResult] = await Promise.allSettled([
        loadImage(bgUrl),
        loadImage(logoUrl),
        loadImage(textureUrl),
      ]);

      if (bgResult.status === 'fulfilled') {
        setBgImg(bgResult.value);
      } else {
        setBgImg(null);
        console.error('[CardGenerator] Failed to load background image:', bgUrl, bgResult.reason);
      }

      if (logoResult.status === 'fulfilled') {
        setLogoImg(logoResult.value);
      } else {
        setLogoImg(null);
        console.error('[CardGenerator] Failed to load logo image:', logoUrl, logoResult.reason);
      }

      if (textureResult.status === 'fulfilled') {
        setTextureImg(textureResult.value);
      } else {
        setTextureImg(null);
        console.error('[CardGenerator] Failed to load grid texture image:', textureUrl, textureResult.reason);
      }

      const isLocalPreview = import.meta.env.DEV && new URLSearchParams(window.location.search).get('preview') === '1';
      const savedAvatar = isLocalPreview ? resolveAssetUrl('hero_figure.webp') : localStorage.getItem('vid_uploaded_avatar');
      if (!savedAvatar) {
        setAvatarImg(null);
        return;
      }

      try {
        const avatarImage = await loadImage(savedAvatar);
        setAvatarImg(avatarImage);
      } catch (error) {
        setAvatarImg(null);
        console.error('[CardGenerator] Failed to load saved avatar image from localStorage.', error);
      }
    };
    loadResources();
  }, [loadImage]);

  const generateQR = useCallback(async () => {
    try {
      const verifyUrl = citizenId
        ? `${siteOrigin}/verify/${citizenId}`
        : siteOrigin;

      const { default: QRCode } = await import('qrcode');
      const qrDataUrl = await QRCode.toDataURL(verifyUrl, {
        width: 240,
        margin: 1,
        color: { dark: '#f18ab5', light: '#00000000' },
        errorCorrectionLevel: 'M',
      });
      const img = await loadImage(qrDataUrl);
      setQrImg(img);
    } catch (e) {
      console.error('QR generation failed:', e);
    }
  }, [citizenId, loadImage, siteOrigin]);

  useEffect(() => {
    generateQR();
  }, [generateQR]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    let cancelled = false;

    void renderCertificateCanvas(canvas, {
      fields: form,
      assets: {
        backgroundImage: bgImg,
        logoImage: logoImg,
        textureImage: textureImg,
        avatarImage: avatarImg,
        qrImage: qrImg,
      },
      copy: cardCopy.canvas,
    }).then((rendered) => {
      if (!cancelled && !rendered) {
        console.error('[CardGenerator] Canvas context unavailable');
      }
    }).catch((err) => {
      if (!cancelled) {
        console.error('[CardGenerator] Failed to render certificate:', err);
      }
    });

    return () => {
      cancelled = true;
    };
  }, [avatarImg, bgImg, cardCopy.canvas, form, logoImg, qrImg, textureImg]);

  const exportPNG = async () => {
    if (isDownloading) return;
    setIsDownloading(true);

    try {
      const canvas = document.createElement('canvas');
      const rendered = await renderCertificateCanvas(canvas, {
        fields: form,
        assets: {
          backgroundImage: bgImg,
          logoImage: logoImg,
          textureImage: textureImg,
          avatarImage: avatarImg,
          qrImage: qrImg,
        },
        copy: cardCopy.canvas,
      }, { dpr: 2 });
      if (!rendered) {
        throw new Error('Canvas context unavailable');
      }

      const imageBlob = await new Promise<Blob>((resolve, reject) => {
        canvas.toBlob((blob) => {
          if (blob) {
            resolve(blob);
          } else {
            reject(new Error('Card image export failed'));
          }
        }, 'image/png');
      });

      const { default: JSZip } = await import('jszip');
      const zip = new JSZip();
      const verifyUrl = citizenId ? `${siteOrigin}/verify/${citizenId}` : siteOrigin;
      const downloadLanguage = getDownloadLanguage(i18n.resolvedLanguage ?? i18n.language);
      const bundleNames = getLocalizedBundleNames(downloadLanguage);
      const verificationGuide = getVerificationGuide(downloadLanguage, form, sha256Hash, verifyUrl);
      let archiveMetadata: ArchiveCertificateMetadata = {};
      let evidenceManifest: EvidenceManifest | null = null;

      if (citizenId) {
        const { data: recordData, error: recordError } = await supabase
          .from('v_ids')
          .select('created_at')
          .eq('friendly_id', citizenId)
          .maybeSingle();

        if (recordError) {
          console.warn('[CardGenerator] Archive certificate metadata unavailable:', recordError);
        } else if (recordData) {
          archiveMetadata = {
            ...archiveMetadata,
            createdAt: String(recordData.created_at || ''),
          };
        }

        const { data: evidenceData, error: evidenceError } = await supabase
          .from('v_id_evidence_materials')
          .select('file_name, material_type, file_size_bytes, sha256_hash, created_at')
          .eq('friendly_id', citizenId);

        if (evidenceError) {
          console.warn('[CardGenerator] Private evidence manifest unavailable:', evidenceError);
        } else if (evidenceData?.length) {
          evidenceManifest = await buildEvidenceManifest(form, evidenceData.map((material) => ({
            file_name: String(material.file_name || ''),
            material_type: String(material.material_type || ''),
            file_size_bytes: Number(material.file_size_bytes || 0),
            sha256_hash: String(material.sha256_hash || ''),
            created_at: String(material.created_at || ''),
          })));
        }
      }

      const archiveCertificatePdf = await buildArchiveCertificatePdf(
        form,
        sha256Hash,
        verifyUrl,
        archiveMetadata,
        downloadLanguage,
        evidenceManifest
      );

      zip.file(bundleNames.identityCard, imageBlob);
      zip.file(bundleNames.archiveCertificate, archiveCertificatePdf);
      zip.file(bundleNames.verificationGuide, verificationGuide);

      if (citizenId) {
        try {
          const { data: otsData, error: otsError } = await supabase.functions.invoke('ots-download', {
            body: { friendly_id: citizenId },
          });
          if (otsData?.ots_file_base64 && otsData?.file_name) {
            const binary = atob(otsData.ots_file_base64);
            const bytes = new Uint8Array(binary.length);
            for (let i = 0; i < binary.length; i += 1) {
              bytes[i] = binary.charCodeAt(i);
            }
            zip.file(otsData.file_name, bytes);
          } else if (otsError || otsData?.error) {
            console.warn('[CardGenerator] OTS file unavailable, continuing without it:', otsError || otsData?.error);
          }
        } catch (error) {
          console.warn('[CardGenerator] OTS file download failed, continuing without it:', error);
        }
      }

      const zipBlob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(zipBlob);
      const link = document.createElement('a');
      link.download = `VAID_${form.serialId}_Complete.zip`;
      link.href = url;
      link.style.display = 'none';
      document.body.appendChild(link);
      link.click();
      link.remove();

      setTimeout(() => URL.revokeObjectURL(url), 100);
    } catch (error) {
      console.error('[CardGenerator] Failed to create download bundle:', error);
      alert(t('cardGenerator.errors.downloadFailed'));
    } finally {
      setIsDownloading(false);
    }
  };

  if (accessError) {
    return (
      <div className="min-h-screen bg-[#0d0d1a] text-white flex items-center justify-center p-6">
        <div className="max-w-md text-center space-y-4">
          <h1 className="text-2xl font-bold">{t('cardGenerator.cannotContinue')}</h1>
          <p className="text-slate-300 leading-relaxed">{accessError}</p>
          <button
            onClick={() => {
              sessionStorage.removeItem(CARD_GENERATOR_SESSION_KEY);
              navigate('/');
            }}
            className="px-5 py-2 bg-blue-600 rounded-lg hover:bg-blue-500 transition-all"
          >
            {t('cardGenerator.backHome')}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen text-white relative overflow-x-hidden bg-[#030713] flex flex-col items-center px-2 sm:px-4">
      <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden" aria-hidden>
        <div
          className="absolute inset-0"
          style={{
            backgroundImage: `
              radial-gradient(circle at 12% 12%, rgba(0, 188, 255, 0.14), transparent 24%),
              radial-gradient(circle at 90% 22%, rgba(255, 46, 72, 0.12), transparent 26%),
              linear-gradient(115deg, rgba(5, 18, 45, 0.95), rgba(3, 7, 19, 0.96) 52%, rgba(4, 10, 25, 0.98))
            `,
            backgroundSize: 'cover, cover, cover',
            backgroundPosition: 'center',
          }}
        />
        <div
          className="absolute inset-0 opacity-35"
          style={{
            backgroundImage: `
              linear-gradient(rgba(42, 150, 255, 0.12) 1px, transparent 1px),
              linear-gradient(90deg, rgba(42, 150, 255, 0.12) 1px, transparent 1px)
            `,
            backgroundSize: '64px 64px',
          }}
        />
        <div className="absolute inset-x-0 top-0 h-px bg-slate-400/22" />
      </div>

      <div className="relative z-10 max-w-[1200px] w-full py-4 sm:p-6 flex justify-between items-center gap-4">
        <h1 className="text-xl font-bold tracking-tight sm:text-2xl">{t('cardGenerator.identityPreview')}</h1>
        <div className="flex gap-4">
          <button
            onClick={exportPNG}
            disabled={isDownloading}
            className="px-5 py-2 bg-blue-600 rounded-lg hover:bg-blue-500 transition-all shadow-lg shadow-blue-500/20 disabled:cursor-wait disabled:opacity-70"
          >
            {isDownloading ? t('cardGenerator.downloading') : t('cardGenerator.download')}
          </button>
        </div>
      </div>
      <canvas
        ref={canvasRef}
        className="relative z-10 block rounded-xl shadow-[0_0_50px_rgba(0,0,0,0.5)]"
        style={{
          width: '100%',
          height: 'auto',
          maxWidth: `${CERTIFICATE_CANVAS_WIDTH}px`,
          maxHeight: 'calc(100svh - 9rem)',
          display: 'block',
        }}
      />
      <p className="relative z-10 mt-6 text-slate-500 text-xs text-center max-w-md leading-relaxed">
        * {t('cardGenerator.recordedBy')}
      </p>
    </div>
  );
}
