import { calculateSHA256 } from './sha256';

export interface FormData {
  name: string;
  status: string;
  issuedDate: string;
  serialId: string;
  description: string;
  qrContent: string;
  qrToken: string;
  qrRecord: string;
}
export interface ArchiveCertificateMetadata {
  createdAt?: string;
  creatorLegalName?: string;
  creatorDocumentNumber?: string;
}

export interface EvidenceMaterialRecord {
  file_name: string;
  material_type: string;
  file_size_bytes: number;
  sha256_hash: string;
  created_at: string;
}

export interface EvidenceManifest {
  materials: EvidenceMaterialRecord[];
  manifestText: string;
  manifestHash: string;
}

function formatDateTime(value?: string): string {
  if (!value) return 'Not available';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

export type DownloadLanguage = 'en' | 'zh' | 'ja';

export function getDownloadLanguage(language?: string): DownloadLanguage {
  if (language?.startsWith('zh')) return 'zh';
  if (language?.startsWith('ja')) return 'ja';
  return 'en';
}

export function getLocalizedBundleNames(language: DownloadLanguage) {
  if (language === 'zh') {
    return {
      identityCard: 'VAID_数字身份卡片.png',
      archiveCertificate: 'VAID_数字身份存档证书.pdf',
      verificationGuide: 'VAID_证明验证说明.txt',
    };
  }

  if (language === 'ja') {
    return {
      identityCard: 'VAID_デジタルアイデンティティカード.png',
      archiveCertificate: 'VAID_デジタルアイデンティティアーカイブ証明書.pdf',
      verificationGuide: 'VAID_証明確認ガイド.txt',
    };
  }

  return {
    identityCard: 'VAID_Digital_Identity_Card.png',
    archiveCertificate: 'VAID_Digital_Identity_Archive_Certificate.pdf',
    verificationGuide: 'VAID_Proof_Verification_Guide.txt',
  };
}

function getArchiveCertificateCopy(language: DownloadLanguage) {
  if (language === 'zh') {
    return {
      htmlLang: 'zh-CN',
      title: 'VAID 数字身份存档证书',
      subtitle: '本证书记录与已下载 VAID 数字身份卡片相关联的数字身份存档信息。',
      sectionTitle: '存档记录',
      statementTitle: '证书说明',
      preservationTitle: '保存说明',
      generatedBy: '由 VAID Protocol 生成',
      fields: {
        recordId: '档案编号',
        characterName: '角色名称',
        creatorLegalName: '创作者真实姓名',
        creatorDocumentNumber: '证件号码',
        createdTime: '创建时间',
        sha256Hash: '图片哈希值',
        publicVerificationUrl: '公开验证链接',
        privateEvidenceMaterials: '私有证据材料',
        evidenceManifestHash: '证据清单哈希值',
      },
      manifestTitle: '私有证据材料清单',
      manifestSubtitle: '本页列出与该 VAID 记录相关联的私有创作证明材料元数据。原始材料文件不包含在本 PDF 中，应由用户自行长期保存。',
      manifestEmpty: '未登记私有证据材料。',
      manifestColumns: {
        fileName: '文件名',
        type: '类型',
        size: '大小',
        sha256Hash: 'SHA-256',
        registeredAt: '登记时间',
      },
      statement: '本文件为 VAID 生成的数字身份存档证书，用于记录说明和辅助证明。它记录档案编号、创建信息、数字指纹和公开验证链接。本文件不等同于版权登记、公证、司法认证、行政确权或任何政府机关出具的权属证明。',
      preservation: '请将本 PDF 证书、数字身份卡片、公开验证链接、原始文件和创作过程材料一并保存。为了隐私安全，VAID 不会保存你的源文件。如发生争议，应结合原始文件、创作过程记录、公开验证页和其他相关证据共同使用。',
    };
  }

  if (language === 'ja') {
    return {
      htmlLang: 'ja',
      title: 'VAID デジタルアイデンティティアーカイブ証明書',
      subtitle: 'この証明書は、ダウンロードされた VAID デジタルアイデンティティカードに関連するアーカイブ記録を要約するものです。',
      sectionTitle: 'アーカイブ記録',
      statementTitle: '証明書の声明',
      preservationTitle: '保存上の注意',
      generatedBy: 'Generated by VAID Protocol',
      fields: {
        recordId: 'Record ID',
        characterName: 'Character Name',
        creatorLegalName: 'Creator Legal Name',
        creatorDocumentNumber: 'Document Number',
        createdTime: 'Created Time',
        sha256Hash: 'SHA-256 Hash',
        publicVerificationUrl: 'Public Verification URL',
        privateEvidenceMaterials: 'Private Evidence Materials',
        evidenceManifestHash: 'Evidence Manifest Hash',
      },
      manifestTitle: 'プライベート証拠資料一覧',
      manifestSubtitle: 'このページは、この VAID レコードに関連する非公開の制作証明資料メタデータを示します。原本ファイルはこの PDF には含まれず、ユーザー自身で長期保存してください。',
      manifestEmpty: 'No private evidence materials registered.',
      manifestColumns: {
        fileName: 'File Name',
        type: 'Type',
        size: 'Size',
        sha256Hash: 'SHA-256',
        registeredAt: 'Registered At',
      },
      statement: 'この文書は、記録説明および補助証拠のために VAID が生成したデジタルアイデンティティアーカイブ証明書です。アーカイブ識別子、作成情報、デジタルフィンガープリント、公開検証リンクを記録します。著作権登録、公証、司法認証、行政上の権利確認、または政府機関による所有権証明に代わるものではありません。',
      preservation: 'この PDF 証明書、デジタルアイデンティティカード、公開検証リンク、原本ファイル、制作過程の資料を一緒に保存してください。プライバシー保護のため、VAID はあなたの原本ファイルを保存しません。紛争が発生した場合は、原本ファイル、制作過程の記録、公開検証ページ、その他の関連証拠とあわせて使用してください。',
    };
  }

  return {
    htmlLang: 'en',
    title: 'VAID Digital Identity Archive Certificate',
    subtitle: 'This certificate summarizes the VAID archive record associated with the downloaded digital identity card.',
    sectionTitle: 'Archive Record',
    statementTitle: 'Certificate Statement',
    preservationTitle: 'Preservation Note',
    generatedBy: 'Generated by VAID Protocol',
    fields: {
      recordId: 'Record ID',
      characterName: 'Character Name',
      creatorLegalName: 'Creator Legal Name',
      creatorDocumentNumber: 'Document Number',
      createdTime: 'Created Time',
      sha256Hash: 'SHA-256 Hash',
      publicVerificationUrl: 'Public Verification URL',
      privateEvidenceMaterials: 'Private Evidence Materials',
      evidenceManifestHash: 'Evidence Manifest Hash',
    },
    manifestTitle: 'Private Evidence Manifest',
    manifestSubtitle: 'This page lists private creation proof material metadata associated with this VAID record. Original material files are not embedded in this PDF and should be retained by the user.',
    manifestEmpty: 'No private evidence materials registered.',
    manifestColumns: {
      fileName: 'File Name',
      type: 'Type',
      size: 'Size',
      sha256Hash: 'SHA-256',
      registeredAt: 'Registered At',
    },
    statement: 'This document is a VAID-generated digital identity archive certificate for record explanation and auxiliary evidence. It records the archive identifier, creation information, digital fingerprint, and public verification link. It does not replace copyright registration, notarization, judicial certification, administrative confirmation, or any government-issued ownership certificate.',
    preservation: 'Keep this PDF certificate, the digital identity card, the public verification link, original files, and creation-process materials together. For privacy and security, VAID does not store your source files. If a dispute occurs, use them together with the original files, creation records, public verification page, and other relevant evidence.',
  };
}

function formatFileSize(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return 'Not available';
  const units = ['B', 'KB', 'MB', 'GB'];
  let value = bytes;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }
  return `${value.toFixed(unitIndex === 0 ? 0 : 2)} ${units[unitIndex]}`;
}

function buildEvidenceManifestText(form: FormData, materials: EvidenceMaterialRecord[]): string {
  return [
    'VAID Private Evidence Manifest',
    `Record ID: ${form.serialId}`,
    `Material Count: ${materials.length}`,
    ...materials.map((material, index) => [
      `Material ${index + 1}`,
      `File Name: ${material.file_name}`,
      `Type: ${material.material_type}`,
      `MIME/Size: ${formatFileSize(Number(material.file_size_bytes))}`,
      `SHA-256: ${material.sha256_hash}`,
      `Registered At: ${formatDateTime(material.created_at)}`,
    ].join('\n')),
  ].join('\n\n');
}

export async function buildEvidenceManifest(
  form: FormData,
  materials: EvidenceMaterialRecord[]
): Promise<EvidenceManifest | null> {
  if (materials.length === 0) return null;
  const sortedMaterials = [...materials].sort((left, right) => {
    const hashCompare = left.sha256_hash.localeCompare(right.sha256_hash);
    if (hashCompare !== 0) return hashCompare;
    return left.file_name.localeCompare(right.file_name);
  });
  const manifestText = buildEvidenceManifestText(form, sortedMaterials);
  return {
    materials: sortedMaterials,
    manifestText,
    manifestHash: await calculateSHA256(manifestText),
  };
}

export function getVerificationGuide(
  language: DownloadLanguage,
  form: FormData,
  sha256Hash: string,
  verifyUrl: string
): string {
  const unavailable = sha256Hash || 'Not available';
  const zh = `VAID 证明验证说明
====================

本下载包用于保存一份 VAID 数字身份记录的本地证明材料。

文件内容：
1. 数字身份卡片 PNG
   用于展示和分享的数字身份卡片。
2. 数字身份存档证书 PDF
   用于记录说明和辅助证明的正式 PDF 证书。
3. 本 TXT 验证说明
   本说明文件。
4. .ots 文件（如存在）
   时间戳证明文件。该文件仅在系统可提供时附带。

核心信息：
Character Name: ${form.name}
Record ID: ${form.serialId}
Created Time: ${form.issuedDate}
SHA-256 Hash: ${unavailable}
Public Verification URL: ${verifyUrl}

如何验证：
1. 打开 Public Verification URL。
2. 对照公开验证页中的 Record ID、Character Name、Created Time 与本下载包是否一致。
3. 对照 SHA-256 Hash 是否一致。
4. 如下载包内包含 .ots 文件，请与本下载包一起保存。
5. 如果 PDF 证书包含 Private Evidence Manifest，请用您自行保存的原始证明材料重新计算 SHA-256，并与清单中的哈希值核对。
6. 原始文件、创作过程截图、录屏、提示词记录、平台记录等材料应由您自行长期保存。

重要说明：
VAID 证书和验证页是记录说明与辅助证明材料，不等同于版权登记、公证、司法认证、行政确权或任何政府机关出具的权属证明。如发生争议，应结合原始文件、创作过程材料、VAID 证书、公开验证页和其他相关证据共同使用。

© VAID Protocol
`;

  const ja = `VAID 証明確認ガイド
====================

このダウンロードパッケージは、VAID デジタルアイデンティティ記録のローカル証明資料を保存するためのものです。

ファイル内容：
1. デジタルアイデンティティカード PNG
   表示および共有用のデジタルアイデンティティカードです。
2. デジタルアイデンティティアーカイブ証明書 PDF
   記録説明および補助証拠のための正式な PDF 証明書です。
3. この TXT 確認ガイド
   この説明ファイルです。
4. .ots ファイル（存在する場合）
   タイムスタンプ証明ファイルです。システムが提供可能な場合のみ同梱されます。

主要情報：
Character Name: ${form.name}
Record ID: ${form.serialId}
Created Time: ${form.issuedDate}
SHA-256 Hash: ${unavailable}
Public Verification URL: ${verifyUrl}

確認方法：
1. Public Verification URL を開きます。
2. 公開検証ページの Record ID、Character Name、Created Time がこのパッケージと一致することを確認します。
3. SHA-256 Hash が一致することを確認します。
4. パッケージに .ots ファイルが含まれる場合は、一緒に保存してください。
5. PDF 証明書に Private Evidence Manifest が含まれる場合は、ご自身で保存した原本証明資料から SHA-256 を再計算し、一覧のハッシュ値と照合してください。
6. 原本ファイル、制作過程のスクリーンショット、画面録画、プロンプト記録、プラットフォーム記録などはご自身で長期保存してください。

重要事項：
VAID 証明書および検証ページは、記録説明と補助証拠のための資料であり、著作権登録、公証、司法認証、行政上の権利確認、または政府機関による所有権証明に代わるものではありません。紛争が発生した場合は、原本ファイル、制作過程資料、VAID 証明書、公開検証ページ、その他の関連証拠とあわせて使用してください。

© VAID Protocol
`;

  const en = `VAID PROOF VERIFICATION GUIDE
=============================

This download package preserves local proof materials for one VAID digital identity record.

Package contents:
1. Digital identity card PNG
   A digital identity card for display and sharing.
2. Digital identity archive certificate PDF
   A formal PDF certificate for record explanation and auxiliary evidence.
3. This TXT verification guide
   This guide.
4. .ots file, if present
   A timestamp proof file included only when available.

Core information:
Character Name: ${form.name}
Record ID: ${form.serialId}
Created Time: ${form.issuedDate}
SHA-256 Hash: ${unavailable}
Public Verification URL: ${verifyUrl}

How to verify:
1. Open the Public Verification URL.
2. Compare the Record ID, Character Name, and Created Time shown on the public verification page with this package.
3. Compare the SHA-256 Hash.
4. If this package includes an .ots file, keep it together with the package.
5. If the PDF certificate includes a Private Evidence Manifest, recompute SHA-256 from your retained original proof materials and compare it with the manifest hashes.
6. Keep original files, creation-process screenshots, screen recordings, prompt records, platform records, and related materials yourself.

Important note:
The VAID certificate and verification page are record explanation and auxiliary proof materials. They do not replace copyright registration, notarization, judicial certification, administrative confirmation, or any government-issued ownership certificate. If a dispute occurs, use them together with original files, creation-process materials, the VAID certificate, the public verification page, and other relevant evidence.

© VAID Protocol
`;

  if (language === 'zh') return `${zh}\n\n${en}\n\n${ja}`;
  if (language === 'ja') return `${ja}\n\n${en}\n\n${zh}`;
  return `${en}\n\n${zh}\n\n${ja}`;
}

function buildJpegPdf(pages: Array<{ jpegBytes: ArrayBuffer; width: number; height: number }>): Blob {
  const pageWidth = 595.28;
  const pageHeight = 841.89;
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
  ];
  const pageObjectNumbers: number[] = [];

  pages.forEach((page, index) => {
    const pageObjectNumber = 3 + index * 3;
    const imageObjectNumber = pageObjectNumber + 1;
    const contentObjectNumber = pageObjectNumber + 2;
    pageObjectNumbers.push(pageObjectNumber);

    const scale = Math.min(pageWidth / page.width, pageHeight / page.height);
    const imageWidth = page.width * scale;
    const imageHeight = page.height * scale;
    const imageX = (pageWidth - imageWidth) / 2;
    const imageY = (pageHeight - imageHeight) / 2;
    const imageArray = new Uint8Array(page.jpegBytes);
    let imageBinary = '';
    for (let i = 0; i < imageArray.length; i += 0x8000) {
      imageBinary += String.fromCharCode(...imageArray.subarray(i, i + 0x8000));
    }
    const imageName = `Im${index}`;
    const contentStream = `q\n${imageWidth.toFixed(2)} 0 0 ${imageHeight.toFixed(2)} ${imageX.toFixed(2)} ${imageY.toFixed(2)} cm\n/${imageName} Do\nQ`;

    objects.push(
      `${pageObjectNumber} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /${imageName} ${imageObjectNumber} 0 R >> >> /Contents ${contentObjectNumber} 0 R >>\nendobj\n`,
      `${imageObjectNumber} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${imageBinary.length} >>\nstream\n${imageBinary}\nendstream\nendobj\n`,
      `${contentObjectNumber} 0 obj\n<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream\nendobj\n`
    );
  });

  objects.splice(
    1,
    0,
    `2 0 obj\n<< /Type /Pages /Kids [${pageObjectNumbers.map((objectNumber) => `${objectNumber} 0 R`).join(' ')}] /Count ${pageObjectNumbers.length} >>\nendobj\n`
  );

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  for (const object of objects) {
    offsets.push(pdf.length);
    pdf += object;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  const bytes = new Uint8Array(pdf.length);
  for (let i = 0; i < pdf.length; i += 1) {
    bytes[i] = pdf.charCodeAt(i) & 0xff;
  }

  return new Blob([bytes], { type: 'application/pdf' });
}

interface ArchiveCertificatePdfField {
  label: string;
  value: string;
  isFingerprint?: boolean;
}

function setPdfFont(ctx: CanvasRenderingContext2D, weight: number, size: number, mono = false) {
  ctx.font = mono
    ? `${weight} ${size}px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace`
    : `${weight} ${size}px "Avenir Next", "Segoe UI", "Noto Sans SC", "Hiragino Sans", Arial, sans-serif`;
}

function drawWrappedText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
  maxLines = 99
) {
  const normalized = String(text || '').replace(/\s+/g, ' ').trim();
  if (!normalized) return y;

  const lines = getWrappedLines(ctx, normalized, maxWidth, maxLines);
  const previousAlign = ctx.textAlign;
  ctx.textAlign = 'left';

  lines.forEach((currentLine, index) => {
    ctx.fillText(currentLine, x, y + index * lineHeight);
  });

  ctx.textAlign = previousAlign;
  return y + lines.length * lineHeight;
}

function getWrappedLines(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
  maxLines = 99
) {
  const normalized = String(text || '').replace(/\s+/g, ' ').trim();
  const lines: string[] = [];
  let line = '';
  const tokens = /[\u3040-\u30ff\u3400-\u9fff]/.test(normalized)
    ? Array.from(normalized)
    : normalized.split(' ');

  for (const token of tokens) {
    const separator = /[\u3040-\u30ff\u3400-\u9fff]/.test(normalized) ? '' : (line ? ' ' : '');
    const nextLine = `${line}${separator}${token}`;
    if (ctx.measureText(nextLine).width <= maxWidth || !line) {
      line = nextLine;
    } else {
      lines.push(line);
      line = token;
      if (lines.length >= maxLines) break;
    }
  }

  if (line && lines.length < maxLines) lines.push(line);
  return lines;
}

function drawCenteredWrappedText(
  ctx: CanvasRenderingContext2D,
  text: string,
  centerX: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
  maxLines = 99
) {
  const lines = getWrappedLines(ctx, text, maxWidth, maxLines);
  const previousAlign = ctx.textAlign;
  ctx.textAlign = 'center';
  lines.forEach((currentLine, index) => {
    ctx.fillText(currentLine, centerX, y + index * lineHeight);
  });
  ctx.textAlign = previousAlign;
  return y + lines.length * lineHeight;
}

function getArchiveCertificateFields(
  form: FormData,
  sha256Hash: string,
  verifyUrl: string,
  metadata: ArchiveCertificateMetadata,
  language: DownloadLanguage,
  evidenceManifest: EvidenceManifest | null
): ArchiveCertificatePdfField[] {
  const copy = getArchiveCertificateCopy(language);
  return [
    { label: copy.fields.recordId, value: form.serialId },
    { label: copy.fields.characterName, value: form.name },
    ...(metadata.creatorLegalName ? [
      { label: copy.fields.creatorLegalName, value: metadata.creatorLegalName },
    ] : []),
    ...(metadata.creatorDocumentNumber ? [
      { label: copy.fields.creatorDocumentNumber, value: metadata.creatorDocumentNumber },
    ] : []),
    { label: copy.fields.createdTime, value: metadata.createdAt ? formatDateTime(metadata.createdAt) : form.issuedDate },
    { label: copy.fields.publicVerificationUrl, value: verifyUrl },
    { label: copy.fields.sha256Hash, value: sha256Hash || 'Not available', isFingerprint: true },
    ...(evidenceManifest ? [
      { label: copy.fields.privateEvidenceMaterials, value: String(evidenceManifest.materials.length) },
      { label: copy.fields.evidenceManifestHash, value: evidenceManifest.manifestHash, isFingerprint: true },
    ] : []),
  ];
}

async function canvasToJpegPage(canvas: HTMLCanvasElement) {
  const jpegBlob = await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) {
        resolve(blob);
      } else {
        reject(new Error('Archive certificate image export failed'));
      }
    }, 'image/jpeg', 0.95);
  });

  return {
    jpegBytes: await jpegBlob.arrayBuffer(),
    width: canvas.width,
    height: canvas.height,
  };
}

function createPdfCanvas() {
  const canvas = document.createElement('canvas');
  canvas.width = 1588;
  canvas.height = 2246;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('Archive certificate canvas unavailable');
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  return { canvas, ctx };
}

async function renderArchiveCertificatePage(
  form: FormData,
  sha256Hash: string,
  verifyUrl: string,
  metadata: ArchiveCertificateMetadata,
  language: DownloadLanguage,
  evidenceManifest: EvidenceManifest | null
) {
  const copy = getArchiveCertificateCopy(language);
  const fields = getArchiveCertificateFields(form, sha256Hash, verifyUrl, metadata, language, evidenceManifest);
  const { canvas, ctx } = createPdfCanvas();
  const left = 168;
  const right = canvas.width - 168;
  const contentWidth = right - left;

  setPdfFont(ctx, 700, 68);
  ctx.fillStyle = '#0f2742';
  ctx.fillText('VAID', left, 230);

  setPdfFont(ctx, 600, 24);
  ctx.fillStyle = '#5c6d80';
  ctx.textAlign = 'right';
  ctx.fillText(`${copy.fields.recordId}: ${form.serialId}`, right, 230);
  ctx.textAlign = 'left';

  ctx.strokeStyle = '#d8e1ea';
  ctx.lineWidth = 4;
  ctx.beginPath();
  ctx.moveTo(left, 294);
  ctx.lineTo(right, 294);
  ctx.stroke();

  setPdfFont(ctx, 700, 56);
  ctx.fillStyle = '#0f2742';
  ctx.textAlign = 'center';
  ctx.fillText(copy.title, canvas.width / 2, 405);

  setPdfFont(ctx, 400, 28);
  ctx.fillStyle = '#5a6878';
  drawCenteredWrappedText(ctx, copy.subtitle, canvas.width / 2, 465, contentWidth - 180, 38, 3);
  ctx.textAlign = 'left';

  setPdfFont(ctx, 700, 30);
  ctx.fillStyle = '#183655';
  ctx.fillText(copy.sectionTitle.toUpperCase(), left, 615);

  let y = 650;
  const labelWidth = 360;
  const rowPaddingX = 30;
  const rowPaddingY = 20;
  const rowMinHeight = 74;
  fields.forEach((field) => {
    setPdfFont(ctx, 700, 24);
    const labelLines = getWrappedLines(ctx, field.label, labelWidth - rowPaddingX * 2, 2).length || 1;
    setPdfFont(ctx, field.isFingerprint ? 500 : 400, field.isFingerprint ? 20 : 25, field.isFingerprint);
    const valueLineHeight = field.isFingerprint ? 30 : 32;
    const valueMaxWidth = contentWidth - labelWidth - rowPaddingX * 2;
    const valueLines = getWrappedLines(ctx, field.value, valueMaxWidth, 3).length || 1;
    const rowHeight = Math.max(
      rowMinHeight,
      Math.min(126, labelLines * 30 + rowPaddingY * 2),
      Math.min(126, valueLines * valueLineHeight + rowPaddingY * 2)
    );

    ctx.fillStyle = '#ffffff';
    ctx.fillRect(left, y, contentWidth, rowHeight);
    ctx.fillStyle = '#f4f7fa';
    ctx.fillRect(left, y, labelWidth, rowHeight);
    ctx.strokeStyle = '#d9e2eb';
    ctx.lineWidth = 2;
    ctx.strokeRect(left, y, contentWidth, rowHeight);

    setPdfFont(ctx, 700, 24);
    ctx.fillStyle = '#58687a';
    drawWrappedText(ctx, field.label, left + rowPaddingX, y + 43, labelWidth - rowPaddingX * 2, 30, 2);

    setPdfFont(ctx, field.isFingerprint ? 500 : 400, field.isFingerprint ? 20 : 25, field.isFingerprint);
    ctx.fillStyle = '#172033';
    drawWrappedText(
      ctx,
      field.value,
      left + labelWidth + rowPaddingX,
      y + 43,
      valueMaxWidth,
      valueLineHeight,
      3
    );
    y += rowHeight;
  });

  const drawTextBox = (title: string, body: string, top: number, boxHeight: number) => {
    setPdfFont(ctx, 700, 30);
    ctx.fillStyle = '#183655';
    ctx.fillText(title.toUpperCase(), left, top);
    ctx.fillStyle = '#f7fafc';
    ctx.fillRect(left, top + 26, contentWidth, boxHeight);
    ctx.strokeStyle = '#d9e2eb';
    ctx.strokeRect(left, top + 26, contentWidth, boxHeight);
    setPdfFont(ctx, 400, 24);
    ctx.fillStyle = '#38485a';
    drawWrappedText(ctx, body, left + 40, top + 82, contentWidth - 80, 34, 5);
  };

  const statementTop = Math.max(y + 70, 1240);
  const statementHeight = 216;
  const preservationTop = statementTop + statementHeight + 128;
  const preservationHeight = 216;

  drawTextBox(copy.statementTitle, copy.statement, statementTop, statementHeight);
  drawTextBox(copy.preservationTitle, copy.preservation, preservationTop, preservationHeight);

  setPdfFont(ctx, 400, 22);
  ctx.fillStyle = '#6c7b8d';
  ctx.fillText(copy.generatedBy, left, 2052);
  ctx.textAlign = 'right';
  ctx.fillText(form.serialId, right, 2052);
  ctx.textAlign = 'left';

  return canvasToJpegPage(canvas);
}

async function renderEvidenceManifestPage(
  form: FormData,
  language: DownloadLanguage,
  evidenceManifest: EvidenceManifest
) {
  const copy = getArchiveCertificateCopy(language);
  const { canvas, ctx } = createPdfCanvas();
  const left = 168;
  const right = canvas.width - 168;
  const contentWidth = right - left;

  setPdfFont(ctx, 700, 68);
  ctx.fillStyle = '#0f2742';
  ctx.fillText('VAID', left, 230);
  setPdfFont(ctx, 600, 24);
  ctx.fillStyle = '#5c6d80';
  ctx.textAlign = 'right';
  ctx.fillText(`${copy.fields.recordId}: ${form.serialId}`, right, 230);
  ctx.textAlign = 'left';
  ctx.strokeStyle = '#d8e1ea';
  ctx.lineWidth = 4;
  ctx.beginPath();
  ctx.moveTo(left, 294);
  ctx.lineTo(right, 294);
  ctx.stroke();

  setPdfFont(ctx, 700, 52);
  ctx.fillStyle = '#0f2742';
  ctx.textAlign = 'center';
  ctx.fillText(copy.manifestTitle, canvas.width / 2, 405);
  ctx.textAlign = 'left';

  setPdfFont(ctx, 400, 25);
  ctx.fillStyle = '#5a6878';
  drawWrappedText(ctx, copy.manifestSubtitle, left + 50, 470, contentWidth - 100, 36, 4);

  let y = 640;
  setPdfFont(ctx, 700, 25);
  ctx.fillStyle = '#38485a';
  ctx.fillText(`${copy.fields.privateEvidenceMaterials}: ${evidenceManifest.materials.length}`, left + 30, y);
  y += 52;
  setPdfFont(ctx, 500, 22, true);
  drawWrappedText(ctx, `${copy.fields.evidenceManifestHash}: ${evidenceManifest.manifestHash}`, left + 30, y, contentWidth - 60, 32, 3);
  y += 125;

  evidenceManifest.materials.slice(0, 8).forEach((material, index) => {
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(left, y, contentWidth, 205);
    ctx.strokeStyle = '#d9e2eb';
    ctx.strokeRect(left, y, contentWidth, 205);
    setPdfFont(ctx, 700, 24);
    ctx.fillStyle = '#172033';
    drawWrappedText(ctx, `${index + 1}. ${material.file_name}`, left + 30, y + 40, contentWidth - 60, 30, 2);
    setPdfFont(ctx, 500, 21);
    ctx.fillStyle = '#38485a';
    ctx.fillText(`${copy.manifestColumns.type}: ${material.material_type}`, left + 30, y + 112);
    ctx.fillText(`${copy.manifestColumns.size}: ${formatFileSize(Number(material.file_size_bytes))}`, left + 30, y + 145);
    setPdfFont(ctx, 500, 19, true);
    drawWrappedText(ctx, `${copy.manifestColumns.sha256Hash}: ${material.sha256_hash}`, left + 30, y + 178, contentWidth - 60, 28, 2);
    y += 225;
  });

  setPdfFont(ctx, 400, 22);
  ctx.fillStyle = '#6c7b8d';
  ctx.fillText(copy.generatedBy, left, 2052);
  ctx.textAlign = 'right';
  ctx.fillText(form.serialId, right, 2052);
  ctx.textAlign = 'left';

  return canvasToJpegPage(canvas);
}

export async function buildArchiveCertificatePdf(
  form: FormData,
  sha256Hash: string,
  verifyUrl: string,
  metadata: ArchiveCertificateMetadata,
  evidenceManifest: EvidenceManifest | null
): Promise<Blob> {
  const pdfPages = [];

  for (const certificateLanguage of ['en', 'zh'] satisfies DownloadLanguage[]) {
    pdfPages.push(await renderArchiveCertificatePage(
      form,
      sha256Hash,
      verifyUrl,
      metadata,
      certificateLanguage,
      evidenceManifest
    ));

    if (evidenceManifest) {
      pdfPages.push(await renderEvidenceManifestPage(form, certificateLanguage, evidenceManifest));
    }
  }

  return buildJpegPdf(pdfPages);
}
